apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: demo-app-prd
namespace: demo-app
nameSuffix: -prd
resources:
#- ../../bases/demo-app
- prd-cluster.yaml
# - namespace.yaml
# - deployment.yaml
# - service.yaml
# transformers:
# - labels.yaml
replicas:
- count: 2
  # name of deployment
  name: hello-eks-a
## if this image used, replace it with this tag
# images:
# - name: gbaeke/flux-rt
#   newTag: sha-11e921f